force-app/main/default/objects/Chat__c.object
<CustomObject>
    <label>Chat</label>
    <nameField>
        <label>Chat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat__c/fields/ChatId__c.field-meta.xml
<CustomField>
    <fullName>ChatId__c</fullName>
    <externalId>true</externalId>
    <label>ChatId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/Chat__c.object
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>

force-app/main/default/objects/Message__c.object
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Chat__c.field-meta.xml
<CustomField>
    <fullName>Chat__c</fullName>
    <label>Chat</label>
    <referenceTo>Chat__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/MessageId__c.field-meta.xml
<CustomField>
    <fullName>MessageId__c</fullName>
    <externalId>true</externalId>
    <label>MessageId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Members</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TelegramQueueable.cls
public without sharing class TelegramQueueable implements Queueable, Database.AllowsCallouts {

    private TelegramBotApi.API_COMMAND command;
    private Object payload;
    private String messageTypeToSave;
    private Boolean pinMessage;

    public TelegramQueueable(TelegramBotApi.API_COMMAND command, Object payload) {
        this.command = command;
        this.payload = payload;
        this.pinMessage = false;
    }

    //for sendMessage only
    public TelegramQueueable setMessageTypeToSave(String messageTypeToSave) {
        this.messageTypeToSave = messageTypeToSave;
        return this;
    }

    //for sendMessage only
    public TelegramQueueable setPinMessage() {
        this.pinMessage = true;
        return this;
    }

    public void execute(QueueableContext qc) {
        try {
            switch on command {
                when sendMessage {
                    TelegramBotApi.Result result = TelegramBotApi.sendMessage((TelegramBotApi.Message)payload);
                    if (result.ok) {
                        if (String.isNotBlank(this.messageTypeToSave)) {
                            saveMessage(result.result);
                        }
                        if (this.pinMessage) {
                            pinMessage(result.result);
                        }
                    } else {
                        Logger.error(result, 'sendMessage result');
                    }
                }
                when pinChatMessage {
                    TelegramBotApi.pinMessage((TelegramBotApi.PinMessage)payload);
                }
                when answerCallbackQuery {
                    TelegramBotApi.answerCallbackQuery((TelegramBotApi.CallbackQuery)payload);
                }
            }
        } catch (Exception e) {
            Logger.error(e, payload, 'TelegramQueueable');
            throw e;
        }
    }

    private void pinMessage(TelegramBotUpdateDTO.TG_Message message) {
        System.enqueueJob(
                new TelegramQueueable(
                        TelegramBotApi.API_COMMAND.pinChatMessage,
                        new TelegramBotApi.PinMessage(message.chat.id, message.message_id)
                )
        );
    }

    private void saveMessage(TelegramBotUpdateDTO.TG_Message message) {
        List<Chat__c> chats = [SELECT Id FROM Chat__c WHERE IsActive__c = true AND ChatId__c = :message.chat.id LIMIT 1];
        if (!chats.isEmpty()) {
            insert new Message__c(
                    Chat__c = chats[0].Id,
                    Type__c = this.messageTypeToSave,
                    MessageId__c = message.message_id
            );
        }
    }
}