force-app/main/default/objects/CrowdFunding__c.object
<CustomObject>
    <label>Crowd Funding</label>
    <nameField>
        <displayFormat>#{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crowd Funding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donate__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CrowdFunding__c</fullName>
        <label>Crowd Funding</label>
        <referenceTo>CrowdFunding__c</referenceTo>
        <relationshipLabel>Donates</relationshipLabel>
        <relationshipName>Donates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DonateId__c</fullName>
        <externalId>true</externalId>
        <label>Donate Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipName>Funds</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Donate</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Donate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/TelegramId__c.field-meta.xml
<CustomField>
    <fullName>TelegramId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Telegram Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TelegramAnswerInlineQueryListener.cls
public without sharing class TelegramAnswerInlineQueryListener implements TelegramBotUpdateListener {

    private Crowdfunding crowdFunding;

    public Boolean isApplicable(TelegramBotUpdateDTO tUpdate) {
        TelegramBotUpdateDTO.TG_CallbackQuery callback = tUpdate.callback_query;
        if (callback == null || callback.message == null) return false;

        try {
            crowdFunding = new Crowdfunding(callback.message.chat.id, callback.message.message_id);
            return crowdFunding.id != null;
        } catch (Exception e) {
            Logger.error(e, 'TelegramAnswerInlineQueryListener.isApplicable ' + callback.message.chat.id + '|' + callback.message.message_id);
            return false;
        }
    }

    public void dispatch(TelegramBotUpdateDTO tUpdate) {
        TelegramBotUpdateDTO.TG_CallbackQuery callback = tUpdate.callback_query;
        try {
            Participant__c participant = TelegramBotService.buildParticipant(callback.tFrom);

            TelegramBotService.upsertParticipant(participant);

            Donate__c donate = new Donate__c(
                    CrowdFunding__c = crowdFunding.id,
                    Participant__c = participant.Id,
                    DonateId__c = crowdFunding.idForReference + participant.TelegramId__c,
                    Amount__c = Decimal.valueOf(callback.data)
            );
            upsert donate Donate__c.DonateId__c;

            TelegramBotApi.CallbackQuery query = new TelegramBotApi.CallbackQuery();
            query.callback_query_id = callback.id;
            query.text = '👍';
            query.show_alert = true;
            System.enqueueJob(new TelegramQueueable(TelegramBotApi.API_COMMAND.answerCallbackQuery, query));

            Crowdfunding fund = new Crowdfunding(callback.message.chat.id, callback.message.message_id);
            System.enqueueJob(new TelegramQueueable(TelegramBotApi.API_COMMAND.sendMessage, fund.buildMessage()));

        } catch (Exception e) {
            TelegramBotApi.CallbackQuery query = new TelegramBotApi.CallbackQuery();
            query.callback_query_id = callback.id;
            query.text = 'Щось пішло не так 😟';
            query.show_alert = true;
            System.enqueueJob(new TelegramQueueable(TelegramBotApi.API_COMMAND.answerCallbackQuery, query));
            Logger.error(e, tUpdate, 'TelegramAnswerInlineQueryListener.dispatch');
        }
    }
}