force-app/main/default/objects/Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <label>Place</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogEvent__e.object
<CustomObject>
    <fields>
        <fullName>JsonLog__c</fullName>
        <label>JsonLog</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>LogEvent</label>
    <pluralLabel>LogEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/Message__c.object
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Members</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/Logger.cls
public with sharing class Logger {
    private static final String DEBUG = 'Debug';
    private static final String ERROR = 'Error';

    public static void error(Object text, String place) {
        log(text.toString(), place, ERROR);
    }

    public static void error(Exception e, Object text, String place) {
        log(e.getMessage() + text.toString(), place, ERROR);
    }

    public static void debug(Object text, String place) {
        log(text.toString(), place, DEBUG);
    }

    public static void debug(String text) {
        debug(text, '');
    }

    private static void log(String text, String place, String type) {
        Log__c log = new Log__c(Message__c = text, Type__c = type, Place__c = place);
        LogEvent__e event = new LogEvent__e(JsonLog__c = JSON.serialize(log));
        EventBus.publish(event);
    }
}