force-app/main/default/objects/Participant__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/FlatNumber__c.field-meta.xml
<CustomField>
    <fullName>FlatNumber__c</fullName>
    <label>Flat Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TelegramLongSettings__mdt.object
<CustomObject>
    <label>Telegram Long Settings</label>
    <pluralLabel>Telegram Long Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TelegramLongSettings__mdt/fields/Help__c.field-meta.xml
<CustomField>
    <fullName>Help__c</fullName>
    <label>Help</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TelegramLongSettings__mdt/fields/NoAccessHelp__c.field-meta.xml
<CustomField>
    <fullName>NoAccessHelp__c</fullName>
    <label>No Access Help</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/TelegramHelpListener.cls
public with sharing class TelegramHelpListener extends TelegramBotUpdateCommandListener {

    TelegramLongSettings__mdt setting;

    public TelegramHelpListener() {
        super(TELEGRAM_COMMAND.Ihelp);
        setting = [SELECT NoAccessHelp__c, Help__c FROM TelegramLongSettings__mdt LIMIT 1];
    }

    public override void dispatch(TelegramBotUpdateDTO tUpdate) {
        TelegramBotUpdateDTO.TG_Message message = tUpdate.message;
        try {
            Participant__c p = TelegramBotService.findParticipant(tUpdate.message.tFrom);

            String text = (p == null || p.FlatNumber__c == null) ? setting.NoAccessHelp__c : setting.Help__c;
            TelegramBotApi.sendMessage(
                    new TelegramBotService.MessageBuilder(message.chat.id)
                            .setText(text)
                            .disableNotifications()
                            .getMessage()
            );

        } catch (Exception e) {
            Logger.error(e, tUpdate.message, 'TelegramHelpListener.dispatch');
        }
    }

}