force-app/main/default/objects/Participant__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/FlatNumber__c.field-meta.xml
<CustomField>
    <fullName>FlatNumber__c</fullName>
    <label>Flat Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/TelegramNewMemberAnswerListener.cls
public with sharing class TelegramNewMemberAnswerListener implements TelegramBotUpdateListener {

    public Boolean isApplicable(TelegramBotUpdateDTO tUpdate) {
        return tUpdate.message != null && tUpdate.message.reply_to_message != null
                && tUpdate.message.reply_to_message.tFrom.username == TelegramBotCallBack.BOT_USERNAME
                && tUpdate.message.reply_to_message.text.startsWith(TelegramNewMemberListener.MESSAGE_STARTS);
    }

    public void dispatch(TelegramBotUpdateDTO tUpdate) {
        TelegramBotUpdateDTO.TG_Message message = tUpdate.message;
        try {
            Integer flatNumber = TelegramBotService.getFlatNumber(message.text);
            if (flatNumber == null) return;

            Participant__c newMember = TelegramBotService.findParticipantFromMentioning(message.reply_to_message, message.tFrom);

            if (newMember != null) {
                newMember.FlatNumber__c = flatNumber;
                TelegramBotService.upsertParticipant(newMember);
                TelegramBotService.sendNewMemberFlatMessage(message.chat.id, message.message_id, newMember);
                TelegramBotService.updateAllMembersMessage(message.chat.id);
            }
        } catch (Exception e) {
            Logger.error(e, message, 'TelegramNewMemberAnswerListener.dispatch');
        }
    }
}