force-app/main/default/objects/Participant__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/FlatNumber__c.field-meta.xml
<CustomField>
    <fullName>FlatNumber__c</fullName>
    <label>Flat Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/TelegramSayMeFromListener.cls
public without sharing class TelegramSayMeFromListener extends TelegramBotUpdateCommandListener {

    public TelegramSayMeFromListener() {
        super(TELEGRAM_COMMAND.Ime);
    }

    public override void dispatch(TelegramBotUpdateDTO tUpdate) {
        TelegramBotUpdateDTO.TG_Message message = tUpdate.message;
        try {
            Integer flatNumber = TelegramBotService.getFlatNumber(message.arguments);
            if (flatNumber == null) return;

            Participant__c participant = TelegramBotService.buildParticipant(message.tFrom);
            participant.FlatNumber__c = flatNumber;
            TelegramBotService.upsertParticipant(participant);

            TelegramBotService.sendNewMemberFlatMessage(message.chat.id, message.message_id, participant);
            TelegramBotService.updateAllMembersMessage(message.chat.id);

        } catch (Exception e) {
            Logger.error(e, message, 'TelegramSayMeFromListener.dispatch');
        }
    }
}