force-app/main/default/objects/Participant__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/ChatId__c.field-meta.xml
<CustomField>
    <fullName>ChatId__c</fullName>
    <externalId>true</externalId>
    <label>Chat Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/SubscribedToBlackoutStartWarning__c.field-meta.xml
<CustomField>
    <fullName>SubscribedToBlackoutStartWarning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribed To Blackout Start Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TelegramSubscribeToBlackout.cls
public with sharing class TelegramSubscribeToBlackout extends TelegramBotUpdateCommandListener {
    private static final String FROM_MESSAGE = '🧐.. {0} квартира.';
    private static final String FROM_MESSAGE_NOT_FOUND = '😟 не зареєстровано.';

    public TelegramSubscribeToBlackout() {
        super(TELEGRAM_COMMAND.Isubscribe);
    }

    public override void dispatch(TelegramBotUpdateDTO tUpdate) {
        //shutdown
        TelegramBotApi.sendMessage(
            new TelegramBotService.MessageBuilder(tUpdate.message.chat.id)
                .setText('Service unavailable')
                .getMessage()
        );
        if (true) return;
        TelegramBotUpdateDTO.TG_Message message = tUpdate.message;
        try {
            Participant__c fromUser = TelegramBotService.findParticipant(message.tFrom);
            if (fromUser == null) return;
            fromUser.ChatId__c = message.chat.id;
            fromUser.SubscribedToBlackoutStartWarning__c = true;
            TelegramBotService.upsertParticipant(fromUser);

            System.enqueueJob(new TelegramQueueable(
                TelegramBotApi.API_COMMAND.sendMessage,
                new TelegramBotService.MessageBuilder(message.chat.id)
                        .setText('Subscribed. To unsubscribe - /unsubscribe')
                        .setReplyToId(message.message_id)
                        .getMessage()
                )
            );

        } catch (Exception e) {
            Logger.error(e, message, 'TelegramSubscribeToBlackout.dispatch' + message.chat.id + ' _ ' + message.tFrom.first_name + ' _ ' + message.tFrom.first_name);
        }
    }
}