force-app/main/default/objects/Participant__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/FlatNumber__c.field-meta.xml
<CustomField>
    <fullName>FlatNumber__c</fullName>
    <label>Flat Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Participant__c.object
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

force-app/main/default/objects/Participant__c/fields/TelegramId__c.field-meta.xml
<CustomField>
    <fullName>TelegramId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Telegram Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Participant__c/fields/TelegramUsername__c.field-meta.xml
<CustomField>
    <fullName>TelegramUsername__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Telegram Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/TelegramTagFlatListener.cls
public without sharing class TelegramTagFlatListener extends TelegramBotUpdateCommandListener {

    private static final String NO_MEMBERS = '` - Ніхто не зареєстрований в цій квартирі.`';

    public TelegramTagFlatListener() {
        super(TELEGRAM_COMMAND.Itag);
    }

    public override void dispatch(TelegramBotUpdateDTO tUpdate) {
        TelegramBotUpdateDTO.TG_Message message = tUpdate.message;
        try {
            Integer flatNumber = TelegramBotService.getFlatNumber(message.arguments);
            if (flatNumber == null) return;

            String text = '';
            for (Participant__c p : [SELECT TelegramUsername__c, TelegramId__c, Name, LastName__c, FlatNumber__c FROM Participant__c WHERE FlatNumber__c = :flatNumber]) {
                text += TelegramBotService.mention(p) + ', ';
            }
            if (String.isBlank(text)) {
                text = flatNumber + NO_MEMBERS;
            } else {
                text = flatNumber + ':' + text.removeEnd(', ');
            }
            System.enqueueJob(
                    new TelegramQueueable(
                            TelegramBotApi.API_COMMAND.sendMessage,
                            new TelegramBotService.MessageBuilder(tUpdate.message.chat.id).setText(text).disableNotifications().getMessage()
                    )
            );
        } catch (Exception e) {
            Logger.error(e, message, 'TelegramTagFlatListener.dispatch');
        }
    }
}