force-app/main/default/objects/Participant__c.object
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/FlatNumber__c.field-meta.xml
<CustomField>
    <fullName>FlatNumber__c</fullName>
    <label>Flat Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TelegramFromFlatListener.cls
public class TelegramFromFlatListener extends TelegramBotUpdateCommandListener {
    private static final String FROM_MESSAGE = '🧐.. {0} квартира.';
    private static final String FROM_MESSAGE_NOT_FOUND = '😟 не зареєстровано.';

    public TelegramFromFlatListener() {
        super(TELEGRAM_COMMAND.Ifrom);
    }

    public override void dispatch(TelegramBotUpdateDTO tUpdate) {
        TelegramBotUpdateDTO.TG_Message message = tUpdate.message;
        Integer flatNumber;
        try {
            Participant__c mentionUser = TelegramBotService.findParticipantFromMentioning(message, message.tFrom);
            if (mentionUser == null) return;

            flatNumber = TelegramBotService.getFlatNumber(message.arguments);
            if (flatNumber == null) {
                mentionUser = TelegramBotService.findParticipant(mentionUser);
                String messageText;
                if (mentionUser != null && mentionUser.FlatNumber__c != null) {
                    messageText = String.format(
                            FROM_MESSAGE,
                            new List<String>{String.valueOf(mentionUser.FlatNumber__c)}
                    );
                } else {
                    messageText = FROM_MESSAGE_NOT_FOUND;
                }
                TelegramBotApi.sendMessage(
                        new TelegramBotService.MessageBuilder(message.chat.id)
                                .setText(messageText)
                                .setReplyToId(message.message_id)
                                .disableNotifications()
                                .getMessage()
                );
            } else if (TelegramBotService.isAdminUser(message.tFrom)) {
                mentionUser.FlatNumber__c = flatNumber;
                TelegramBotService.upsertParticipant(mentionUser);
                TelegramBotService.updateAllMembersMessage(message.chat.id);
            }
        } catch (Exception e) {
            Logger.error(e, message, 'TelegramFromFlatListener.dispatch' + flatNumber);
        }
    }
}